name: Build LaTeX and deploy on GitHub Releases
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Build-LaTeX:
    runs-on: ubuntu-20.04
    steps:
      - uses: DanySK/compile-and-publish-all-latex@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
